### ISSUE TITLE
Possible Problem

### ISSUE THREAD

**Issue by yonimn2000** [sterlingwalker/humanocity-server#13]
https://github.com/sterlingwalker/humanocity-server/blob/d8d3170b39996d784bf90f2e37a929b0728fb7a5/src/main/java/com/management/HumanResources/service/CreateService.java#L51-L59

Won't checking if the ID is 0 cause an issue later? I think it will always be 0 there when you create a new feedback.

**Comment by sterlingwalker** [comment]
For the client side of things I was intending to have it so that the employee would have to enter their `id` or it's grabbed automatically from props. So if we sent the following object in React:
```js
let data = {
employeeId: 2748272849,
type: 'Request',
description: 'We need more people in our department'
}
```

It would assign the `employeeId` accordingly along with the other values. And this code would initialize the `feedbackId`. The only time `employeeId` would be 0 is if we don't specify, which constitutes a bad request since we wouldn't know who it came from.

**Comment by yonimn2000** [comment]
Oops, sorry. I misread it. You are right. My bad...
